### ISSUE TITLE
Caching errors

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#374] opened 2021-07-23 05:23 UTC
Version: 0.15.0

I am passing plugin paths dynamically (see #372) via `--plugins /tmp/plugin.wasm`. On the next execution `dprint` seems to try and remove plugins it knows:

```
Error reading plugin file bytes. Forgetting from cache and retrying. Message: Error reading file /Users/joscha/Library/Caches/dprint/cache/plugins/dprint-plugin-markdown/dprint-plugin-markdown-0.9.2.cached: No such file or directory (os error 2)
Error forgetting plugin: Error deleting file /Users/joscha/Library/Caches/dprint/cache/plugins/dprint-plugin-markdown/dprint-plugin-markdown-0.9.2.cached: No such file or directory (os error 2)
```

- it seems that locally passed plugins are somehow stored in the cache. The plugins I am passing are content-addressed, e.g. each plugin has a unique path, e.g.: ` /nix/store/94m3xrclpn29k4isrf6zjg0mlbyxs9ja-typescript.wasm` - so when the plugin contents change, the path changes.

Can I open a PR to:
* Allows disabling the cache via the dprint.json and/or (preferred) a command line flag?
* Disable caching for plugins passed via `--plugins` that are NOT urls
* If the two above ones are a bad idea because there is an additional compile step I am not aware of, a flag to disable the warnings?

cc @declanvong @uri-canva

**Comment by joscha** [comment] 2021-07-23 12:22
Ran into this again when trying to start dprint from a read-only filesystem:
```
Error creating cache directory: Error("Error creating directory /homeless-shelter/Library/Caches/dprint/cache: Read-only file system (os error 30)")
```

**Comment by dsherret** [comment] 2021-07-29 00:18
I opened #375 and #376. If you would like to open a PR for #376 please feel free or I will get to it soon.

I would like to investigate why this error is happening. It seems the cache file is getting out of date with the cache or something. Are the plugin contents changing and the version is remaining the same? Even still, it should work. I'll investigate on the weekend (it might be helpful if you could attach the two wasm files of the plugin and before and after in case I have trouble reproducing).

By the way, I'll get back to your email probably on the weekend and work out the CLA thing soon.

**Comment by dsherret** [comment] 2021-07-31 18:18
A temporary workaround for this is to call `dprint clear-cache` each time. That said, this issue is occuring because the cache key changes because the file path changes. I will look into a fix.

**Comment by dsherret** [comment] 2021-08-01 01:00
Tried this out just now and I wasn't able to reproduce. I removed all the log messages though (moved to verbose). It would be good to get some reproduction steps for this one to find out what the problem is.

**Comment by joscha** [comment] 2021-08-04 03:39
will try out how it behaves with verbose logging, thank you!

**Comment by dsherret** [comment] 2021-08-07 22:42
I looked at the code today and the only way I can see this happening is:

1. The ".cached" file is deleted between runs.
2. The plugin changes its version without a new build happening (so file hash doesn't change).
3. Maybe there are two processes running at the same time that cause this to happen?

Regardless (expect for point 3), the dprint CLI will handle this gracefully and won't output any log messages anymore. I think we can just close this one and not bother looking into it further unless it is reproducible or causes some noticable slowdown.

**Closed by dsherret** 2021-08-07 22:42 UTC

**Comment by joscha** [comment] 2021-08-07 23:53
Thanks for looking into this!
