### ISSUE TITLE
Broken plugin detection with `dprint fmt <path containing "[]">`

### ISSUE THREAD

**Issue by SnO2WMaN** [dprint/dprint#568] opened 2022-10-11 11:07 UTC
It seems that plugin detection does not work well for file paths containing `[]`, which is often the case with Next.js.

Here is a more accrete description of behavior.

The file structure is as follows (example).

```
src
└ pages
  ├ index.page.tsx
  └ user/[id]/index.page.tsx
```

When I try to format running with like `dprint fmt src/user/[id]/index.page.tsx`, the error occured with this below message and can't format.

```
No files found to format with the specified plugins. You may want to try using `dprint output-file-paths` to see which files it's finding.
```

Oddly, `dprint fmt` without the file specify, format will success.

The result of `dprint output-file-paths` and `dprint -v`, and `dprint.json`(excerpt)

```bash
$ dprint output-file-paths
/.../src/pages/user/[id]/index.page.tsx
/.../src/pages/index.page.tsx
```

Version: 0.32.1
```
$ dprint -v
dprint 0.32.1
```

```json
{
  "typescript": {
  },
  "includes": [
    "**/*.{ts,tsx,js,jsx,cjs,mjs}",
    "**/*.{json,md,toml}"
  ],
  "excludes": [
    "**/.direnv",
    "**/.next",
    "**/node_modules",
    "**/*-lock.json",
    "**/next-env.d.ts"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.74.0.wasm",
    "https://plugins.dprint.dev/json-0.15.3.wasm",
    "https://plugins.dprint.dev/markdown-0.13.3.wasm",
    "https://plugins.dprint.dev/toml-0.5.4.wasm"
  ]
}
```

**Comment by dsherret** [comment] 2022-10-15 22:38
I think this is a duplicate of #552

**Closed** 2022-10-15 22:39 UTC
Labels: duplicate
