### ISSUE TITLE
Support range formatting

### ISSUE THREAD

**Issue by azherebtsov** [dprint/dprint#464] opened 2022-02-04 21:15 UTC
Now that we have https://github.com/dprint/dprint-vscode and https://github.com/dprint/dprint-intellij and other editors support, it makes sense to have a way to format only portion of the file.
Possible use cases:
1. User selects a portion of the file in the IDE (editor) and triggers reformatting of this piece of text only
2. Reformatting only lines changed in a given commit
3. Reformatting a `*.diff` without even looking into original files (ranges of a diff can be reformatted by applying different plugins)

It might be beneficial for large code repositories where "re-format the world" approach is not an option.

Plugin to choose for a given range can be inferred from the file name as it is happening now.

**Comment by dsherret** [comment] 2022-02-06 18:17
It's a lot of work to implement this and get support in plugins. Additionally, most dprint plugins format files in under 10ms. For very large files like TypeScript's checker.ts (44,000 lines) I believe it took ~800ms last time I looked.

This change would also require a breaking change to the plugin interfaces and I'm not sure it's worth the complexity given how fast dprint is at formatting an entire file. That said, perhaps dprint editor plugins could attempt to format the selected range which should work in certain scenarios (ex. when formatting statements). The problem is that these plugins would need to have some context about what kind of file is being edited and it would probably just end up frustrating users.

**Comment by azherebtsov** [comment] 2022-02-06 22:50
Thank you David! 
These all are good arguments!
Another argument for range formatting is that (1) sometimes formatters are not consistent, and sometimes (2) the configuration of the formatter is changed. In both cases the engineer will try to avoid diffs in the lines they have not touched in a particular change (PR, commit), especially if they caused by an auto-formatter; therefore, they will want to run formatter on the limited range. 

In the case (2) it is not always desired to have "reformat the world commit", everybody hates them (lots of conflicts, hard to merge it, messed up history).

No pressure on this feature just now, as you correctly pointed execution time allows to reformat the whole file with the assumption that plugin output is consistent.

**Comment by dsherret** [comment] 2024-09-07 08:29
This has been fully implemented in dprint for a few months now as of (https://github.com/dprint/dprint/pull/858), but many of the plugins don't support it. Going to close this one as it's done in dprint itself.

**Closed by dsherret** 2024-09-07 08:29 UTC
Labels: enhancement
